package meaning.emoji.com.emojimeaning;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.ListView;

import java.util.ArrayList;

public class AnimalsNatureActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.words_list);

        ArrayList<Word> words = new ArrayList<Word>();
        words.add(new Word("See-No-Evil Monkey", R.drawable.see_no_evil_monkey));
        words.add(new Word("Hear-No-Evil Monkey", R.drawable.hear_no_evil_monkey));
        words.add(new Word("Monkey Face", R.drawable.monkey_face));
        words.add(new Word("Monkey", R.drawable.monkey));
        words.add(new Word("Gorilla", R.drawable.gorilla));
        words.add(new Word("Dog Face", R.drawable.dog_face));
        words.add(new Word("Dog", R.drawable.dog));
        words.add(new Word("Poodle",R.drawable.poodle));
        words.add(new Word("Wolf Face",R.drawable.wolf_face));
        words.add(new Word("Fox Face",R.drawable.fox_face));
        words.add(new Word("Cat Face",R.drawable.cat_face));
        words.add(new Word("Cat",R.drawable.cat));
        words.add(new Word("Lion Face",R.drawable.lion_face));
        words.add(new Word("Tiger Face",R.drawable.tiger_face));
        words.add(new Word("Tiger",R.drawable.tiger));
        words.add(new Word("Leopard",R.drawable.leopard));
        words.add(new Word("Horse Face",R.drawable.horse_face));
        words.add(new Word("Horse",R.drawable.horse));
        words.add(new Word("Unicorn Face",R.drawable.unicorn_face));
        words.add(new Word("Cow Face",R.drawable.cow_face));
        words.add(new Word("Ox",R.drawable.ox));
        words.add(new Word("Water Buffalo",R.drawable.water_buffalo));
        words.add(new Word("Cow",R.drawable.cow));
        words.add(new Word("Pig Face",R.drawable.pig_face));
        words.add(new Word("Pig",R.drawable.pig));
        words.add(new Word("Boar",R.drawable.boar));
        words.add(new Word("Pig Nose",R.drawable.pig_nose));
        words.add(new Word("Ram",R.drawable.ram));
        words.add(new Word("Sheep",R.drawable.sheep));
        words.add(new Word("Goat",R.drawable.goat));
        words.add(new Word("Camel",R.drawable.dromedary_camel));
        words.add(new Word("Two-Hump Camel",R.drawable.bactrian_camel));
        words.add(new Word("Elephant",R.drawable.elephant));
        words.add(new Word("Rhinoceros",R.drawable.rhinoceros));
        words.add(new Word("Mouse Face",R.drawable.mouse_face));
        words.add(new Word("Mouse",R.drawable.mouse));
        words.add(new Word("Rat",R.drawable.rat));
        words.add(new Word("Hamster Face",R.drawable.hamster_face));
        words.add(new Word("Rabbit Face",R.drawable.rabbit_face));
        words.add(new Word("Rabbit",R.drawable.rabbit));
        words.add(new Word("Chipmunk",R.drawable.chipmunk));
        words.add(new Word("Bat",R.drawable.bat));
        words.add(new Word("Bear Face",R.drawable.bear_face));
        words.add(new Word("Koala",R.drawable.koala));
        words.add(new Word("Panda Face",R.drawable.panda_face));
        words.add(new Word("Paw Prints",R.drawable.paw_prints));
        words.add(new Word("Turkey",R.drawable.turkey));
        words.add(new Word("Chicken",R.drawable.chicken));
        words.add(new Word("Rooster",R.drawable.rooster));
        words.add(new Word("Hatching Chick",R.drawable.hatching_chick));
        words.add(new Word("Baby Chick",R.drawable.baby_chick));
        words.add(new Word("Front-Facing Baby Chick",R.drawable.front_facing_baby_chick));
        words.add(new Word("Bird",R.drawable.bird));
        words.add(new Word("Penguin",R.drawable.penguin));
        words.add(new Word("Dove",R.drawable.dove_of_peace));
        words.add(new Word("Eagle",R.drawable.eagle));
        words.add(new Word("Duck",R.drawable.duck));
        words.add(new Word("Owl",R.drawable.owl));
        words.add(new Word("Frog Face",R.drawable.frog_face));
        words.add(new Word("Crocodile",R.drawable.crocodile));
        words.add(new Word("Turtle",R.drawable.turtle));
        words.add(new Word("Lizard",R.drawable.lizard));
        words.add(new Word("Sanke",R.drawable.snake));
        words.add(new Word("Dragon Face",R.drawable.dragon_face));
        words.add(new Word("Dragon",R.drawable.dragon));
        words.add(new Word("Spouting Whale",R.drawable.spouting_whale));
        words.add(new Word("Whale",R.drawable.whale));
        words.add(new Word("Dolphin",R.drawable.dolphin));
        words.add(new Word("Fish",R.drawable.fish));
        words.add(new Word("Tropical Fish",R.drawable.tropical_fish));
        words.add(new Word("Blow Fish",R.drawable.blowfish));
        words.add(new Word("Octopus",R.drawable.octopus));
        words.add(new Word("Spiral Shell",R.drawable.spiral_shell));
        words.add(new Word("Crab",R.drawable.crab));
        words.add(new Word("Shrimp",R.drawable.shrimp));
        words.add(new Word("Squid",R.drawable.squid));
        words.add(new Word("Snail",R.drawable.snail));
        words.add(new Word("Butterfly",R.drawable.butterfly));
        words.add(new Word("Bug",R.drawable.bug));
        words.add(new Word("Ant",R.drawable.ant));
        words.add(new Word("Honeybee",R.drawable.honeybee));
        words.add(new Word("Lady Beetle",R.drawable.lady_beetle));
        words.add(new Word("Spider",R.drawable.spider));
        words.add(new Word("Spider Web",R.drawable.spider_web));
        words.add(new Word("Scorpion",R.drawable.scorpion));
        words.add(new Word("Bouquet",R.drawable.bouquet));
        words.add(new Word("Cherry Blossom",R.drawable.cherry_blossom));
        words.add(new Word("White Flower",R.drawable.white_flower));
        words.add(new Word("Rosette",R.drawable.rosette));
        words.add(new Word("Rose",R.drawable.rose));
        words.add(new Word("Wilted Flower",R.drawable.wilted_flower));
        words.add(new Word("Hibiscus",R.drawable.hibiscus));
        words.add(new Word("Sunflower",R.drawable.sunflower));
        words.add(new Word("Blossom",R.drawable.blossom));
        words.add(new Word("Tulip",R.drawable.tulip));
        words.add(new Word("Seeding",R.drawable.seedling));
        words.add(new Word("Evergreen Tree",R.drawable.evergreen_tree));
        words.add(new Word("Deciduoud Tree",R.drawable.deciduous_tree));
        words.add(new Word("Palm Tree",R.drawable.palm_tree));
        words.add(new Word("Cactus",R.drawable.cactus));
        words.add(new Word("Sheaf of Rice",R.drawable.ear_of_rice));
        words.add(new Word("Herb",R.drawable.herb));
        words.add(new Word("Shamrock",R.drawable.shamrock));
        words.add(new Word("Four Leaf Clover",R.drawable.four_leaf_clover));
        words.add(new Word("Maple Leaf",R.drawable.maple_leaf));
        words.add(new Word("Fallen Leaf",R.drawable.fallen_leaf));
        words.add(new Word("Leaf Fluttering in Wind",R.drawable.leaf_fluttering_in_wind));
        words.add(new Word("Mushroom",R.drawable.mushroom));
        words.add(new Word("Chestnut",R.drawable.chestnut));
        words.add(new Word("Globe Showing Europe-Africa",R.drawable.earth_globe_europe_africa));
        words.add(new Word("Globe Showing Americas",R.drawable.earth_globe_americas));
        words.add(new Word("Globe Showing Asia-Australia",R.drawable.earth_globe_asia_australia));
        words.add(new Word("Globe With Meridians",R.drawable.globe_with_meridians));
        words.add(new Word("New Moon",R.drawable.new_moon_symbol));
        words.add(new Word("Waxing Crescent Moon",R.drawable.waxing_crescent_moon_symbol));
        words.add(new Word("First Quarter Moon",R.drawable.first_quarter_moon_symbol));
        words.add(new Word("Waxing Gibbous Moon",R.drawable.waning_gibbous_moon_symbol));
        words.add(new Word("Full Moon",R.drawable.full_moon_symbol));
        words.add(new Word("Waning Gibbous Moon",R.drawable.waxing_gibbous_moon_symbol));
        words.add(new Word("Last Quarter Moon",R.drawable.last_quarter_moon_symbol));
        words.add(new Word("Waning Crescent Moon",R.drawable.waning_crescent_moon_symbol));
        words.add(new Word("Crescent Moon",R.drawable.crescent_moon));
        words.add(new Word("New Moon Face",R.drawable.new_moon_with_face));
        words.add(new Word("First Quarter Moon With Face",R.drawable.first_quarter_moon_with_face));
        words.add(new Word("Last Quarter Moon With Face",R.drawable.last_quarter_moon_with_face));
        words.add(new Word("Sun",R.drawable.sunrise));
        words.add(new Word("Full Moon With Face",R.drawable.full_moon_with_face));
        words.add(new Word("Sun With Face",R.drawable.sun_with_face));
        words.add(new Word("White Medium Star",R.drawable.white_medium_star));
        words.add(new Word("Glowing Star",R.drawable.glowing_star));
        words.add(new Word("Shooting Star",R.drawable.shooting_star));
        words.add(new Word("Cloud",R.drawable.cloud));
        words.add(new Word("Sun Behind Cloud",R.drawable.sun_behind_cloud));
        words.add(new Word("Cloud With Lightning and Rain",R.drawable.thunder_cloud_and_rain));
        words.add(new Word("Sun Behind Small Cloud",R.drawable.white_sun_with_small_cloud));
        words.add(new Word("Sun Behind Large Cloud",R.drawable.white_sun_behind_cloud));
        words.add(new Word("Sun Behind Rain Cloud",R.drawable.white_sun_behind_cloud_with_rain));
        words.add(new Word("Cloud With Rain",R.drawable.cloud_with_rain));
        words.add(new Word("Cloud With Snow",R.drawable.cloud_with_snow));
        words.add(new Word("Cloud With Lightning",R.drawable.cloud_with_lightning));
        words.add(new Word("Tornado",R.drawable.cloud_with_tornado));
        words.add(new Word("Fog",R.drawable.fog));
        words.add(new Word("Wind Face",R.drawable.wind_blowing_face));
        words.add(new Word("Rainbow",R.drawable.rainbow));
        words.add(new Word("Umbrella",R.drawable.umbrella));
        words.add(new Word("Umbrella With Rain Drops",R.drawable.umbrella_with_rain_drops));
        words.add(new Word("High Voltage",R.drawable.high_voltage_sign));
        words.add(new Word("Snowflake",R.drawable.snowflake));
        words.add(new Word("Snowman",R.drawable.snowman));
        words.add(new Word("Snowman Without Snow",R.drawable.snowman_without_snow));
        words.add(new Word("Comet",R.drawable.comet));
        words.add(new Word("Fire",R.drawable.fire));
        words.add(new Word("Droplet",R.drawable.droplet));
        words.add(new Word("Water Wave",R.drawable.water_wave));
        words.add(new Word("Christmas Tree",R.drawable.christmas_tree));
        words.add(new Word("Sparkles",R.drawable.sparkles));
        words.add(new Word("Tanabata Tree",R.drawable.tanabata_tree));
        words.add(new Word("Pine Decoration",R.drawable.pine_decoration));
        words.add(new Word("Speak-No-Evil Monkey", R.drawable.speak_no_evil_monkey));
        words.add(new Word("Collision", R.drawable.collision_symbol));
        words.add(new Word("Sweat Droplets", R.drawable.droplet));
        words.add(new Word("Dashing Away", R.drawable.dash_symbol));
        words.add(new Word("Dizzy", R.drawable.dizzy_symbol));

        MeaningAdapter adapter = new MeaningAdapter(this, words, R.color.category_smileys_people);

        ListView listView = (ListView) findViewById(R.id.meaning_list_1);

        listView.setAdapter(adapter);

    }
}
