package meaning.emoji.com.emojimeaning;

import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;
import android.widget.ListView;

import java.util.ArrayList;

public class FlagsActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.words_list);

        ArrayList<Word> words = new ArrayList<Word>();
        words.add(new Word("Chequered Flag", R.drawable.chequered_flag));
        words.add(new Word("Triangular Flag",R.drawable.triangular_flag_on_post));
        words.add(new Word("Crossed Flags",R.drawable.crossed_flags));
        words.add(new Word("Black Flag",R.drawable.waving_black_flag));
        words.add(new Word("White Flag",R.drawable.waving_white_flag));
        words.add(new Word("Rainbow Flag",R.drawable.rainbow_flag));
        words.add(new Word("Ascension Island",R.drawable.flag_for_ascension_island));
        words.add(new Word("Andorra",R.drawable.flag_for_andorra));
        words.add(new Word("United Arab Emirates",R.drawable.flag_for_united_arab_emirates));
        words.add(new Word("Afghanistan",R.drawable.flag_for_afghanistan));
        words.add(new Word("Antigua & Barbuda",R.drawable.flag_for_antigua_barbuda));
        words.add(new Word("Anguilla",R.drawable.flag_for_anguilla));
        words.add(new Word("Albania",R.drawable.flag_for_albania));
        words.add(new Word("Armenia",R.drawable.flag_for_armenia));
        words.add(new Word("Angola",R.drawable.flag_for_angola));
        words.add(new Word("Antarctica",R.drawable.flag_for_antarctica));
        words.add(new Word("Argentina",R.drawable.flag_for_argentina));
        words.add(new Word("American Samoa",R.drawable.flag_for_american_samoa));
        words.add(new Word("Austria",R.drawable.flag_for_austria));
        words.add(new Word("Australia",R.drawable.flag_for_australia));
        words.add(new Word("Aruba",R.drawable.flag_for_aruba));
        words.add(new Word("Åland Islands",R.drawable.flag_for_aland_islands));
        words.add(new Word("Azerbaijan",R.drawable.flag_for_azerbaijan));
        words.add(new Word("Bosnia & Herzegovina",R.drawable.flag_for_bosnia_herzegovina));
        words.add(new Word("Barbados",R.drawable.flag_for_barbados));
        words.add(new Word("Bangladesh",R.drawable.flag_for_bangladesh));
        words.add(new Word("Belgium",R.drawable.flag_for_belgium));
        words.add(new Word("Burkina Faso",R.drawable.flag_for_burkina_faso));
        words.add(new Word("Bulgaria",R.drawable.flag_for_bulgaria));
        words.add(new Word("Bahrain",R.drawable.flag_for_bahrain));
        words.add(new Word("Burundi",R.drawable.flag_for_burundi));
        words.add(new Word("Benin",R.drawable.flag_for_benin));
        words.add(new Word("St. Barthélemy",R.drawable.flag_for_st_barthelemy));
        words.add(new Word("Bermuda",R.drawable.flag_for_bermuda));
        words.add(new Word("Brunei",R.drawable.flag_for_brunei));
        words.add(new Word("Bolivia",R.drawable.flag_for_bolivia));
        words.add(new Word("Caribbean Netherlands",R.drawable.flag_for_caribbean_netherlands));
        words.add(new Word("Brazil",R.drawable.flag_for_brazil));
        words.add(new Word("Bahamas",R.drawable.flag_for_bahamas));
        words.add(new Word("Bhutan",R.drawable.flag_for_bhutan));
        words.add(new Word("Bouvet Island",R.drawable.flag_for_bouvet_island));
        words.add(new Word("Botswana",R.drawable.flag_for_botswana));
        words.add(new Word("Belarus",R.drawable.flag_for_belarus));
        words.add(new Word("Belize",R.drawable.flag_for_belize));
        words.add(new Word("Canada",R.drawable.flag_for_canada));
        words.add(new Word("Cocos (Keeling) Islands",R.drawable.flag_for_cocos_islands));
        words.add(new Word("Congo - Kinshasa",R.drawable.flag_for_congo_kinshasa));
        words.add(new Word("Central African Republic",R.drawable.flag_for_central_african_republic));
        words.add(new Word("Congo - Brazzaville",R.drawable.flag_for_congo_brazzaville));
        words.add(new Word("Switzerland",R.drawable.flag_for_switzerland));
        words.add(new Word("Côte D’Ivoire",R.drawable.flag_for_cote_divoire));
        words.add(new Word("Cook Islands",R.drawable.flag_for_cook_islands));
        words.add(new Word("Chile",R.drawable.flag_for_chile));
        words.add(new Word("Cameroon",R.drawable.flag_for_cameroon));
        words.add(new Word("China",R.drawable.flag_for_china));
        words.add(new Word("Colombia",R.drawable.flag_for_colombia));
        words.add(new Word("Clipperton Island",R.drawable.flag_for_clipperton_island));
        words.add(new Word("Costa Rica",R.drawable.flag_for_costa_rica));
        words.add(new Word("Cuba",R.drawable.flag_for_cuba));
        words.add(new Word("Cape Verde",R.drawable.flag_for_cape_verde));
        words.add(new Word("Curaçao",R.drawable.flag_for_curacao));
        words.add(new Word("Christmas Island",R.drawable.flag_for_christmas_island));
        words.add(new Word("Cyprus",R.drawable.flag_for_cyprus));
        words.add(new Word("Czechia",R.drawable.flag_for_czech_republic));
        words.add(new Word("Germany",R.drawable.flag_for_germany));
        words.add(new Word("Diego Garcia",R.drawable.flag_for_diego_garcia));
        words.add(new Word("Djibouti",R.drawable.flag_for_djibouti));
        words.add(new Word("Denmark",R.drawable.flag_for_denmark));
        words.add(new Word("Dominica",R.drawable.flag_for_dominica));
        words.add(new Word("Dominican Republic",R.drawable.flag_for_dominican_republic));
        words.add(new Word("Algeria",R.drawable.flag_for_algeria));
        words.add(new Word("Ceuta & Melilla",R.drawable.flag_for_ceuta_melilla));
        words.add(new Word("Ecuador",R.drawable.flag_for_ecuador));
        words.add(new Word("Estonia",R.drawable.flag_for_estonia));
        words.add(new Word("Egypt",R.drawable.flag_for_egypt));
        words.add(new Word("Western Sahara",R.drawable.flag_for_western_sahara));
        words.add(new Word("Eritrea",R.drawable.flag_for_eritrea));
        words.add(new Word("Spain",R.drawable.flag_for_spain));
        words.add(new Word("Ethiopia",R.drawable.flag_for_ethiopia));
        words.add(new Word("European Union",R.drawable.flag_for_european_union));
        words.add(new Word("Finland",R.drawable.flag_for_finland));
        words.add(new Word("Fiji",R.drawable.flag_for_fiji));
        words.add(new Word("Falkland Islands",R.drawable.flag_for_falkland_islands));
        words.add(new Word("Micronesia",R.drawable.flag_for_micronesia));
        words.add(new Word("Faroe Islands",R.drawable.flag_for_faroe_islands));
        words.add(new Word("France",R.drawable.flag_for_france));
        words.add(new Word("Gabon",R.drawable.flag_for_gabon));
        words.add(new Word("United Kingdom",R.drawable.flag_for_united_kingdom));
        words.add(new Word("Grenada",R.drawable.flag_for_grenada));
        words.add(new Word("Georgia",R.drawable.flag_for_georgia));
        words.add(new Word("French Guiana",R.drawable.flag_for_french_guiana));
        words.add(new Word("Guernsey",R.drawable.flag_for_guernsey));
        words.add(new Word("Ghana",R.drawable.flag_for_ghana));
        words.add(new Word("Gibraltar",R.drawable.flag_for_gibraltar));
        words.add(new Word("Greenland",R.drawable.flag_for_greenland));
        words.add(new Word("Gambia",R.drawable.flag_for_gambia));
        words.add(new Word("Guinea",R.drawable.flag_for_guinea));
        words.add(new Word("Guadeloupe",R.drawable.flag_for_guadeloupe));
        words.add(new Word("Equatorial Guinea",R.drawable.flag_for_equatorial_guinea));
        words.add(new Word("Greece",R.drawable.flag_for_greece));
        words.add(new Word("South Georgia & South Sandwich Islands",R.drawable.flag_for_south_georgia_south_sandwich_islands));
        words.add(new Word("Guatemala",R.drawable.flag_for_guatemala));
        words.add(new Word("Guam",R.drawable.flag_for_guam));
        words.add(new Word("Guinea-Bissau",R.drawable.flag_for_guinea_bissau));
        words.add(new Word("Guyana",R.drawable.flag_for_guyana));
        words.add(new Word("Hong Kong Sar China",R.drawable.flag_for_hong_kong));
        words.add(new Word("Heard & Mcdonald Islands",R.drawable.flag_for_heard_mcdonald_islands));
        words.add(new Word("Honduras",R.drawable.flag_for_honduras));
        words.add(new Word("Croatia",R.drawable.flag_for_croatia));
        words.add(new Word("Haiti",R.drawable.flag_for_haiti));
        words.add(new Word("Hungary",R.drawable.flag_for_hungary));
        words.add(new Word("Canary Islands",R.drawable.flag_for_canary_islands));
        words.add(new Word("Indonesia",R.drawable.flag_for_indonesia));
        words.add(new Word("Ireland",R.drawable.flag_for_ireland));
        words.add(new Word("Israel",R.drawable.flag_for_israel));
        words.add(new Word("Isle of Man",R.drawable.flag_for_isle_of_man));
        words.add(new Word("India",R.drawable.flag_for_india));
        words.add(new Word("British Indian Ocean Territory",R.drawable.flag_for_british_indian_ocean_territory));
        words.add(new Word("Iraq",R.drawable.flag_for_iraq));
        words.add(new Word("Iran",R.drawable.flag_for_iran));
        words.add(new Word("Iceland",R.drawable.flag_for_iceland));
        words.add(new Word("Italy",R.drawable.flag_for_italy));
        words.add(new Word("Jersey",R.drawable.flag_for_jersey));
        words.add(new Word("Jamaica",R.drawable.flag_for_jamaica));
        words.add(new Word("Jordan",R.drawable.flag_for_jordan));
        words.add(new Word("Kenya",R.drawable.flag_for_kenya));
        words.add(new Word("Kyrgyzstan",R.drawable.flag_for_kyrgyzstan));
        words.add(new Word("Cambodia",R.drawable.flag_for_cambodia));
        words.add(new Word("Kiribati",R.drawable.flag_for_kiribati));
        words.add(new Word("Comoros",R.drawable.flag_for_comoros));
        words.add(new Word("St. Kitts & Nevis",R.drawable.flag_for_st_kitts_nevis));
        words.add(new Word("North Korea",R.drawable.flag_for_north_korea));
        words.add(new Word("South Korea",R.drawable.flag_for_south_korea));
        words.add(new Word("Kuwait",R.drawable.flag_for_kuwait));
        words.add(new Word("Cayman Islands",R.drawable.flag_for_cayman_islands));
        words.add(new Word("Kazakhstan",R.drawable.flag_for_kazakhstan));
        words.add(new Word("Laos",R.drawable.flag_for_laos));
        words.add(new Word("Lebanon",R.drawable.flag_for_lebanon));
        words.add(new Word("St. Lucia",R.drawable.flag_for_st_lucia));
        words.add(new Word("Liechtenstein",R.drawable.flag_for_liechtenstein));
        words.add(new Word("Sri Lanka",R.drawable.flag_for_sri_lanka));
        words.add(new Word("Liberia",R.drawable.flag_for_liberia));
        words.add(new Word("Lesotho",R.drawable.flag_for_lesotho));
        words.add(new Word("Lithuania",R.drawable.flag_for_lithuania));
        words.add(new Word("Luxembourg",R.drawable.flag_for_luxembourg));
        words.add(new Word("Latvia",R.drawable.flag_for_latvia));
        words.add(new Word("Libya",R.drawable.flag_for_libya));
        words.add(new Word("Morocco",R.drawable.flag_for_morocco));
        words.add(new Word("Monaco",R.drawable.flag_for_monaco));
        words.add(new Word("Moldova",R.drawable.flag_for_moldova));
        words.add(new Word("Montenegro",R.drawable.flag_for_montenegro));
        words.add(new Word("St. Martin",R.drawable.flag_for_st_martin));
        words.add(new Word("Madagascar",R.drawable.flag_for_madagascar));
        words.add(new Word("Marshall Islands",R.drawable.flag_for_marshall_islands));
        words.add(new Word("Macedonia",R.drawable.flag_for_macedonia));
        words.add(new Word("Mali",R.drawable.flag_for_mali));
        words.add(new Word("Myanmar (Burma)",R.drawable.flag_for_myanmar));
        words.add(new Word("Mongolia",R.drawable.flag_for_mongolia));
        words.add(new Word("Macau Sar China",R.drawable.flag_for_macau));
        words.add(new Word("Northern Mariana Islands",R.drawable.flag_for_northern_mariana_islands));
        words.add(new Word("Martinique",R.drawable.flag_for_martinique));
        words.add(new Word("Mauritania",R.drawable.flag_for_mauritania));
        words.add(new Word("Montserrat",R.drawable.flag_for_montserrat));
        words.add(new Word("Malta",R.drawable.flag_for_malta));
        words.add(new Word("Mauritius",R.drawable.flag_for_mauritius));
        words.add(new Word("Maldives",R.drawable.flag_for_maldives));
        words.add(new Word("Malawi",R.drawable.flag_for_malawi));
        words.add(new Word("Mexico",R.drawable.flag_for_mexico));
        words.add(new Word("Malaysia",R.drawable.flag_for_malaysia));
        words.add(new Word("Mozambique",R.drawable.flag_for_mozambique));
        words.add(new Word("Namibia",R.drawable.flag_for_namibia));
        words.add(new Word("New Caledonia",R.drawable.flag_for_new_caledonia));
        words.add(new Word("Niger",R.drawable.flag_for_niger));
        words.add(new Word("Norfolk Island",R.drawable.flag_for_norfolk_island));
        words.add(new Word("Nigeria",R.drawable.flag_for_nigeria));
        words.add(new Word("Nicaragua",R.drawable.flag_for_nicaragua));
        words.add(new Word("Netherlands",R.drawable.flag_for_netherlands));
        words.add(new Word("Norway",R.drawable.flag_for_norway));
        words.add(new Word("Nepal",R.drawable.flag_for_nepal));
        words.add(new Word("Nauru",R.drawable.flag_for_nauru));
        words.add(new Word("Niue",R.drawable.flag_for_niue));
        words.add(new Word("New Zealand",R.drawable.flag_for_new_zealand));
        words.add(new Word("Oman",R.drawable.flag_for_oman));
        words.add(new Word("Panama",R.drawable.flag_for_panama));
        words.add(new Word("Peru",R.drawable.flag_for_peru));
        words.add(new Word("French Polynesia",R.drawable.flag_for_french_polynesia));
        words.add(new Word("Papua New Guinea",R.drawable.flag_for_papua_new_guinea));
        words.add(new Word("Philippines",R.drawable.flag_for_philippines));
        words.add(new Word("Pakistan",R.drawable.flag_for_pakistan));
        words.add(new Word("Poland",R.drawable.flag_for_poland));
        words.add(new Word("St. Pierre & Miquelon",R.drawable.flag_for_st_pierre_miquelon));
        words.add(new Word("Pitcairn Islands",R.drawable.flag_for_pitcairn_islands));
        words.add(new Word("Puerto Rico",R.drawable.flag_for_puerto_rico));
        words.add(new Word("Palestinian Territories",R.drawable.flag_for_palestinian_territories));
        words.add(new Word("Portugal",R.drawable.flag_for_portugal));
        words.add(new Word("Palau",R.drawable.flag_for_palau));
        words.add(new Word("Moldova",R.drawable.flag_for_moldova));
        words.add(new Word("Qatar",R.drawable.flag_for_qatar));
        words.add(new Word("Réunion",R.drawable.flag_for_reunion));
        words.add(new Word("Romania",R.drawable.flag_for_romania));
        words.add(new Word("Serbia",R.drawable.flag_for_serbia));
        words.add(new Word("Russia",R.drawable.flag_for_russia));
        words.add(new Word("Rwanda",R.drawable.flag_for_rwanda));
        words.add(new Word("Saudi Arabia",R.drawable.flag_for_saudi_arabia));
        words.add(new Word("Solomon Islands",R.drawable.flag_for_solomon_islands));
        words.add(new Word("Seychelles",R.drawable.flag_for_seychelles));
        words.add(new Word("Sudan",R.drawable.flag_for_sudan));
        words.add(new Word("Sweden",R.drawable.flag_for_sweden));
        words.add(new Word("Singapore",R.drawable.flag_for_singapore));
        words.add(new Word("St. Helena",R.drawable.flag_for_st_helena));
        words.add(new Word("Slovenia",R.drawable.flag_for_slovenia));
        words.add(new Word("Svalbard & Jan Mayen",R.drawable.flag_for_svalbard_jan_mayen));
        words.add(new Word("Slovakia",R.drawable.flag_for_slovakia));
        words.add(new Word("Sierra Leone",R.drawable.flag_for_sierra_leone));
        words.add(new Word("San Marino",R.drawable.flag_for_san_marino));
        words.add(new Word("Senegal",R.drawable.flag_for_senegal));
        words.add(new Word("Somalia",R.drawable.flag_for_somalia));
        words.add(new Word("Suriname",R.drawable.flag_for_suriname));
        words.add(new Word("South Sudan",R.drawable.flag_for_south_sudan));
        words.add(new Word("São Tomé & Príncipe",R.drawable.flag_for_sao_tome_principe));
        words.add(new Word("El Salvador",R.drawable.flag_for_el_salvador));
        words.add(new Word("Sint Maarten",R.drawable.flag_for_sint_maarten));
        words.add(new Word("Syria",R.drawable.flag_for_syria));
        words.add(new Word("Swaziland",R.drawable.flag_for_swaziland));
        words.add(new Word("Tristan Da Cunha",R.drawable.flag_for_tristan_da_cunha));
        words.add(new Word("Turks & Caicos Islands",R.drawable.flag_for_turks_caicos_islands));
        words.add(new Word("Chad",R.drawable.flag_for_chad));
        words.add(new Word("French Southern Territories",R.drawable.flag_for_french_southern_territories));
        words.add(new Word("Togo",R.drawable.flag_for_togo));
        words.add(new Word("Thailand",R.drawable.flag_for_thailand));
        words.add(new Word("Tajikistan",R.drawable.flag_for_tajikistan));
        words.add(new Word("Tokelau",R.drawable.flag_for_tokelau));
        words.add(new Word("Timor-Leste",R.drawable.flag_for_timor_leste));
        words.add(new Word("Turkmenistan",R.drawable.flag_for_turkmenistan));
        words.add(new Word("Tunisia",R.drawable.flag_for_tunisia));
        words.add(new Word("Tonga",R.drawable.flag_for_tonga));
        words.add(new Word("Turkey",R.drawable.turkey));
        words.add(new Word("Trinidad & Tobago",R.drawable.flag_for_trinidad_tobago));
        words.add(new Word("Tuvalu",R.drawable.flag_for_tuvalu));
        words.add(new Word("Taiwan",R.drawable.flag_for_taiwan));
        words.add(new Word("Tanzania",R.drawable.flag_for_tanzania));
        words.add(new Word("Ukraine",R.drawable.flag_for_ukraine));
        words.add(new Word("Uganda",R.drawable.flag_for_uganda));
        words.add(new Word("U.S. Outlying Islands",R.drawable.flag_for_us_outlying_islands));
        words.add(new Word("United Nations",R.drawable.flag_for_united_nations));
        words.add(new Word("United States",R.drawable.flag_for_united_states));
        words.add(new Word("Uruguay",R.drawable.flag_for_uruguay));
        words.add(new Word("Uzbekistan",R.drawable.flag_for_uzbekistan));
        words.add(new Word("Vatican City",R.drawable.flag_for_vatican_city));
        words.add(new Word("St. Vincent & Grenadines",R.drawable.flag_for_st_vincent_grenadines));
        words.add(new Word("Venezuela",R.drawable.flag_for_venezuela));
        words.add(new Word("British Virgin Islands",R.drawable.flag_for_british_virgin_islands));
        words.add(new Word("U.S. Virgin Islands",R.drawable.flag_for_us_virgin_islands));
        words.add(new Word("Vietnam",R.drawable.flag_for_vietnam));
        words.add(new Word("Vanuatu",R.drawable.flag_for_vanuatu));
        words.add(new Word("Wallis & Futuna",R.drawable.flag_for_wallis_futuna));
        words.add(new Word("Samoa",R.drawable.flag_for_samoa));
        words.add(new Word("Kosovo",R.drawable.flag_for_kosovo));
        words.add(new Word("Yemen",R.drawable.flag_for_yemen));
        words.add(new Word("Mayotte",R.drawable.flag_for_mayotte));
        words.add(new Word("South Africa",R.drawable.flag_for_south_africa));
        words.add(new Word("Zambia",R.drawable.flag_for_zambia));
        words.add(new Word("Zimbabwe",R.drawable.flag_for_zimbabwe));
        words.add(new Word("Flag for England (GB-ENG)",R.drawable.flag_for_england));
        words.add(new Word("Flag for Scotland (GB-SCT)",R.drawable.flag_for_scotland));
        words.add(new Word("Flag for Wales (GB-WLS)",R.drawable.flag_for_wales));
        words.add(new Word("Pirate Flag",R.drawable.pirate_flag));

        MeaningAdapter adapter = new MeaningAdapter(this, words, R.color.category_smileys_people);

        ListView listView = (ListView) findViewById(R.id.meaning_list_1);

        listView.setAdapter(adapter);

    }
}
