package meaning.emoji.com.emojimeaning;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.ListView;

import java.util.ArrayList;

public class ObjectsActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.words_list);

        ArrayList<Word> words = new ArrayList<Word>();
        words.add(new Word("Skull and Crossbones", R.drawable.skull_and_crossbones));
        words.add(new Word("Person Taking Bath",R.drawable.bath));
        words.add(new Word("Person in Bed",R.drawable.sleeping_accommodation));
        words.add(new Word("Love Letter",R.drawable.love_letter));
        words.add(new Word("Bomb",R.drawable.bomb));
        words.add(new Word("Hole",R.drawable.hole));
        words.add(new Word("Shopping Bags",R.drawable.shopping_bags));
        words.add(new Word("Prayer Beads",R.drawable.prayer_beads));
        words.add(new Word("Gem Stone",R.drawable.gem_stone));
        words.add(new Word("Kitchen Knife",R.drawable.hocho));
        words.add(new Word("Amphora",R.drawable.amphora));
        words.add(new Word("World Map",R.drawable.world_map));
        words.add(new Word("Barber Pole",R.drawable.barber_pole));
        words.add(new Word("Framed Picture",R.drawable.frame_with_picture));
        words.add(new Word("Bellhop Bell",R.drawable.bellhop_bell));
        words.add(new Word("Door",R.drawable.door));
        words.add(new Word("Bed",R.drawable.bed));
        words.add(new Word("Couch and Lamp",R.drawable.couch_and_lamp));
        words.add(new Word("Toilet",R.drawable.toilet));
        words.add(new Word("Shower",R.drawable.shower));
        words.add(new Word("Bathtub",R.drawable.bathtub));
        words.add(new Word("Hourglass",R.drawable.hourglass));
        words.add(new Word("Hourglass With Flowing Sand",R.drawable.hourglass_with_flowing_sand));
        words.add(new Word("Watch",R.drawable.watch));
        words.add(new Word("Alarm Clock",R.drawable.alarm_clock));
        words.add(new Word("Stopwatch",R.drawable.stopwatch));
        words.add(new Word("Timer Clock",R.drawable.timer_clock));
        words.add(new Word("Mantelpiece Clock",R.drawable.mantelpiece_clock));
        words.add(new Word("Thermometer",R.drawable.thermometer));
        words.add(new Word("Umbrella on Ground",R.drawable.umbrella_on_ground));
        words.add(new Word("Balloon",R.drawable.balloon));
        words.add(new Word("Party Popper",R.drawable.party_popper));
        words.add(new Word("Confetti Ball",R.drawable.confetti_ball));
        words.add(new Word("Japanese Dolls",R.drawable.japanese_dolls));
        words.add(new Word("Carp Streamer",R.drawable.carp_streamer));
        words.add(new Word("Wind Chime",R.drawable.wind_chime));
        words.add(new Word("Ribbon",R.drawable.ribbon));
        words.add(new Word("Wrapped Gift",R.drawable.wrapped_present));
        words.add(new Word("Joystick",R.drawable.joystick));
        words.add(new Word("Postal Horn",R.drawable.postal_horn));
        words.add(new Word("Studio Microphone",R.drawable.studio_microphone));
        words.add(new Word("Level Slider",R.drawable.level_slider));
        words.add(new Word("Control Knobs",R.drawable.control_knobs));
        words.add(new Word("Radio",R.drawable.radio));
        words.add(new Word("Mobile Phone",R.drawable.mobile_phone));
        words.add(new Word("Mobile Phone With Arrow",R.drawable.mobile_phone_with_rightwards_arrow_at_left));
        words.add(new Word("Telephone",R.drawable.black_telephone));
        words.add(new Word("Telephone Receiver",R.drawable.telephone_receiver));
        words.add(new Word("Pager",R.drawable.pager));
        words.add(new Word("Laptop Computer",R.drawable.personal_computer));
        words.add(new Word("Desktop Computer",R.drawable.desktop_computer));
        words.add(new Word("Printer",R.drawable.printer));
        words.add(new Word("Keyboard",R.drawable.keyboard));
        words.add(new Word("Computer Mouse",R.drawable.three_button_mouse));
        words.add(new Word("Trackball",R.drawable.trackball));
        words.add(new Word("Computer Disk",R.drawable.minidisc));
        words.add(new Word("Floppy Disk",R.drawable.floppy_disk));
        words.add(new Word("Optical Disk",R.drawable.optical_disc));
        words.add(new Word("DVD",R.drawable.dvd));
        words.add(new Word("Movie Camera",R.drawable.movie_camera));
        words.add(new Word("Film Frames",R.drawable.film_frames));
        words.add(new Word("Film Projector",R.drawable.film_projector));
        words.add(new Word("Television",R.drawable.television));
        words.add(new Word("Camera",R.drawable.camera));
        words.add(new Word("Camera With Flash",R.drawable.camera_with_flash));
        words.add(new Word("Video Camera",R.drawable.video_camera));
        words.add(new Word("Videocassette",R.drawable.videocassette));
        words.add(new Word("Left-Pointing Magnifying Glass",R.drawable.left_pointing_magnifying_glass));
        words.add(new Word("Right-Pointing Magnifying Glass",R.drawable.right_pointing_magnifying_glass));
        words.add(new Word("Microscope",R.drawable.microscope));
        words.add(new Word("Telescope",R.drawable.telescope));
        words.add(new Word("Satellite Antenna",R.drawable.satellite_antenna));
        words.add(new Word("Candle",R.drawable.candle));
        words.add(new Word("Light Bulb",R.drawable.electric_light_bulb));
        words.add(new Word("Flashlight",R.drawable.camera_with_flash));
        words.add(new Word("Red Paper Lantern",R.drawable.izakaya_lantern));
        words.add(new Word("Notebook With Decorative Cover",R.drawable.notebook_with_decorative_cover));
        words.add(new Word("Closed Book",R.drawable.closed_book));
        words.add(new Word("Open Book",R.drawable.open_book));
        words.add(new Word("Green Book",R.drawable.green_book));
        words.add(new Word("Blue Book",R.drawable.blue_book));
        words.add(new Word("Orange Book",R.drawable.orange_book));
        words.add(new Word("Books",R.drawable.books));
        words.add(new Word("Notebook",R.drawable.notebook));
        words.add(new Word("Page With Curl",R.drawable.page_with_curl));
        words.add(new Word("Scroll",R.drawable.scroll));
        words.add(new Word("Page Facing Up",R.drawable.page_facing_up));
        words.add(new Word("Newspaper",R.drawable.newspaper));
        words.add(new Word("Rolled-Up Newspaper",R.drawable.rolled_up_newspaper));
        words.add(new Word("Bookmark Tabs",R.drawable.bookmark_tabs));
        words.add(new Word("Bookmark",R.drawable.bookmark));
        words.add(new Word("Label",R.drawable.label));
        words.add(new Word("Money Bag",R.drawable.money_bag));
        words.add(new Word("Yen Banknote",R.drawable.banknote_with_yen_sign));
        words.add(new Word("Dollar Banknote",R.drawable.banknote_with_dollar_sign));
        words.add(new Word("Euro Banknote",R.drawable.banknote_with_euro_sign));
        words.add(new Word("Pound Banknote",R.drawable.banknote_with_pound_sign));
        words.add(new Word("Money With Wings",R.drawable.money_with_wings));
        words.add(new Word("Credit Card",R.drawable.credit_card));
        words.add(new Word("Envelope",R.drawable.envelope));
        words.add(new Word("E-Mail",R.drawable.e_mail_symbol));
        words.add(new Word("Incoming Envelope",R.drawable.incoming_envelope));
        words.add(new Word("Envelope With Arrow",R.drawable.envelope_with_downwards_arrow_above));
        words.add(new Word("Outbox Tray",R.drawable.outbox_tray));
        words.add(new Word("Inbox Tray",R.drawable.inbox_tray));
        words.add(new Word("Package",R.drawable.parcel));
        words.add(new Word("Closed Mailbox With Raised Flag",R.drawable.closed_mailbox_with_raised_flag));
        words.add(new Word("Closed Mailbox With Lowered Flag",R.drawable.closed_mailbox_with_lowered_flag));
        words.add(new Word("Open Mailbox With Raised Flag",R.drawable.open_mailbox_with_raised_flag));
        words.add(new Word("Open Mailbox With Lowered Flag",R.drawable.open_mailbox_with_lowered_flag));
        words.add(new Word("Postbox",R.drawable.postbox));
        words.add(new Word("Ballot Box With Ballot",R.drawable.ballot_box_with_ballot));
        words.add(new Word("Pencil",R.drawable.pencil));
        words.add(new Word("Black Nib",R.drawable.black_nib));
        words.add(new Word("Fountain Pen",R.drawable.lower_left_fountain_pen));
        words.add(new Word("Pen",R.drawable.lock_with_ink_pen));
        words.add(new Word("Paintbrush",R.drawable.lower_left_paintbrush));
        words.add(new Word("Crayon",R.drawable.lower_left_crayon));
        words.add(new Word("Memo",R.drawable.memo));
        words.add(new Word("File Folder",R.drawable.file_folder));
        words.add(new Word("Open File Folder",R.drawable.open_file_folder));
        words.add(new Word("Card Index Dividers",R.drawable.card_index_dividers));
        words.add(new Word("Calendar",R.drawable.calendar));
        words.add(new Word("Tear-Off Calendar",R.drawable.tear_off_calendar));
        words.add(new Word("Spiral Notepad",R.drawable.spiral_note_pad));
        words.add(new Word("Spiral Calendar",R.drawable.spiral_calendar_pad));
        words.add(new Word("Card Index",R.drawable.card_index));
        words.add(new Word("Chart Increasing",R.drawable.chart_with_upwards_trend));
        words.add(new Word("Chart Decreasing",R.drawable.chart_with_downwards_trend));
        words.add(new Word("Bar Chart",R.drawable.bar_chart));
        words.add(new Word("Clipboard",R.drawable.clipboard));
        words.add(new Word("Pushpin",R.drawable.pushpin));
        words.add(new Word("Round Pushpin",R.drawable.round_pushpin));
        words.add(new Word("Paperclip",R.drawable.paperclip));
        words.add(new Word("Linked Paperclips",R.drawable.linked_paperclips));
        words.add(new Word("Straight Ruler",R.drawable.straight_ruler));
        words.add(new Word("Triangular Ruler",R.drawable.triangular_ruler));
        words.add(new Word("Scissors",R.drawable.black_scissors));
        words.add(new Word("Card File Box",R.drawable.card_file_box));
        words.add(new Word("File Cabinet",R.drawable.file_cabinet));
        words.add(new Word("Wastebasket",R.drawable.wastebasket));
        words.add(new Word("Locked",R.drawable.closed_lock_with_key));
        words.add(new Word("Unlocked",R.drawable.open_lock));
        words.add(new Word("Locked With Pen",R.drawable.lock_with_ink_pen));
        words.add(new Word("Locked With Key",R.drawable.closed_lock_with_key));
        words.add(new Word("Key",R.drawable.key));
        words.add(new Word("Old Key",R.drawable.old_key));
        words.add(new Word("Hammer",R.drawable.hammer));
        words.add(new Word("Pick",R.drawable.pick));
        words.add(new Word("Hammer and Pick",R.drawable.hammer_and_pick));
        words.add(new Word("Hammer and Wrench",R.drawable.hammer_and_wrench));
        words.add(new Word("Dagger",R.drawable.dagger_knife));
        words.add(new Word("Crossed Swords",R.drawable.crossed_swords));
        words.add(new Word("Pistol",R.drawable.pistol));
        words.add(new Word("Shield",R.drawable.shield));
        words.add(new Word("Wrench",R.drawable.wrench));
        words.add(new Word("Nut and Bolt",R.drawable.nut_and_bolt));
        words.add(new Word("Gear",R.drawable.gear));
        words.add(new Word("Clamp",R.drawable.compression));
        words.add(new Word("Alembic",R.drawable.alembic));
        words.add(new Word("Balance Scale",R.drawable.scales));
        words.add(new Word("Link",R.drawable.link_symbol));
        words.add(new Word("Chains",R.drawable.chains));
        words.add(new Word("Syringe",R.drawable.syringe));
        words.add(new Word("Pill",R.drawable.pill));
        words.add(new Word("Cigarette",R.drawable.smoking_symbol));
        words.add(new Word("Coffin",R.drawable.coffin));
        words.add(new Word("Funeral Urn", R.drawable.funeral_urn));
        words.add(new Word("Moai",R.drawable.moyai));
        words.add(new Word("Oil Drum",R.drawable.oil_drum));
        words.add(new Word("Crystal Ball",R.drawable.crystal_ball));
        words.add(new Word("Potable Water",R.drawable.potable_water_symbol));
        words.add(new Word("Chequered Flag",R.drawable.chequered_flag));
        words.add(new Word("Triangular Flag",R.drawable.triangular_flag_on_post));
        words.add(new Word("Crossed Flags",R.drawable.crossed_flags));
        words.add(new Word("Black Flag",R.drawable.waving_black_flag));
        words.add(new Word("White Flag",R.drawable.waving_white_flag));
        words.add(new Word("Rainbow Flag",R.drawable.rainbow_flag));


        MeaningAdapter adapter = new MeaningAdapter(this, words, R.color.category_smileys_people);

        ListView listView = (ListView) findViewById(R.id.meaning_list_1);

        listView.setAdapter(adapter);

    }
}
