package meaning.emoji.com.emojimeaning;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.ListView;

import java.util.ArrayList;

public class SmileyPeopleActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.words_list);

        ArrayList<Word> words = new ArrayList<Word>();
        words.add(new Word("Grinning Face", R.drawable.grinningface));
        words.add(new Word("Grinning Face With Smiling Eyes", R.drawable.grinningfacewithsmilingeyes));
        words.add(new Word("Face With Tears of Joy", R.drawable.facewithtearsofjoy));
        words.add(new Word("Rolling on the Floor Laughing", R.drawable.rollingonthefloorlaughing));
        words.add(new Word("Smiling Face With Open Mouth", R.drawable.smilingfacewithopenmouth));
        words.add(new Word("Smiling Face With Open Mouth & Smiling Eyes", R.drawable.smilingfacewithopenmouthandsmilingeyes));
        words.add(new Word("Smiling Face With Open Mouth & Cold Sweat", R.drawable.smilingfacewithopenmouthandcoldsweat));
        words.add(new Word("Smiling Face With Open Mouth & Closed Eyes", R.drawable.smilingfacewithopenmouthandtightlyclosedeyes));
        words.add(new Word("Winking Face", R.drawable.winkingface));
        words.add(new Word("Smiling Face With Smiling Eyes", R.drawable.smilingfacewithsmilingeyes));
        words.add(new Word("Face Savouring Delicious Food", R.drawable.facesavouringdeliciousfood));
        words.add(new Word("Smiling Face With Sunglasses", R.drawable.smiling_face_with_sunglasses));
        words.add(new Word("Smiling Face With Heart-Eyes",R.drawable.smiling_face_with_heart_shaped_eyes ));
        words.add(new Word("Face Blowing a Kiss",R.drawable.face_throwing_a_kiss));
        words.add(new Word("Kissing Face",R.drawable.kissing_face));
        words.add(new Word("Kissing Face With Smiling Eyes",R.drawable.kissing_face_with_smiling_eyes));
        words.add(new Word("Kissing Face With Closed Eyes",R.drawable.kissing_face_with_closed_eyes));
        words.add(new Word("Smiling Face",R.drawable.white_smiling_face));
        words.add(new Word("Slightly Smiling Face",R.drawable.slightly_smiling_face));
        words.add(new Word("Hugging Face",R.drawable.hugging_face));
        words.add(new Word("Thinking Face",R.drawable.thinking_face));
        words.add(new Word("Neutral Face",R.drawable.neutral_face));
        words.add(new Word("Expressionless Face",R.drawable.expressionless_face));
        words.add(new Word("Face Without Mouth",R.drawable.face_without_mouth));
        words.add(new Word("Face With Rolling Eyes",R.drawable.face_with_rolling_eyes));
        words.add(new Word("Smirking Face",R.drawable.smirking_face));
        words.add(new Word("Persevering Face",R.drawable.persevering_face));
        words.add(new Word("Disappointed but Relieved Face",R.drawable.disappointed_but_relieved_face));
        words.add(new Word("Face With Open Mouth",R.drawable.face_with_open_mouth));
        words.add(new Word("Zipper-Mouth Face",R.drawable.zipper_mouth_face));
        words.add(new Word("Hushed Face",R.drawable.hushed_face));
        words.add(new Word("Sleepy Face",R.drawable.sleepy_face));
        words.add(new Word("Tired Face",R.drawable.tired_face));
        words.add(new Word("Sleeping Face",R.drawable.sleeping_face));
        words.add(new Word("Relieved Face",R.drawable.relieved_face));
        words.add(new Word("Face With Stuck-Out Tongue",R.drawable.face_with_stuck_out_tongue));
        words.add(new Word("Face With Stuck-Out Tongue & Winking Eye",R.drawable.face_with_stuck_out_tongue_and_winking_eye));
        words.add(new Word("Face With Stuck-Out Tongue & Closed Eyes",R.drawable.face_with_stuck_out_tongue_and_tightly_closed_eyes));
        words.add(new Word("Drooling Face",R.drawable.drooling_face));
        words.add(new Word("Unamused Face",R.drawable.unamused_face));
        words.add(new Word("Face With Cold Sweat",R.drawable.face_with_cold_sweat));
        words.add(new Word("Pensive Face",R.drawable.pensive_face));
        words.add(new Word("Confused Face",R.drawable.confused_face));
        words.add(new Word("Upside-Down Face",R.drawable.upside_down_face));
        words.add(new Word("Money-Mouth Face",R.drawable.money_mouth_face));
        words.add(new Word("Astonished Face",R.drawable.astonished_face));
        words.add(new Word("Frowning Face",R.drawable.white_frowning_face));
        words.add(new Word("Slightly Frowning Face",R.drawable.slightly_frowning_face));
        words.add(new Word("Confounded Face",R.drawable.confounded_face));
        words.add(new Word("Disappointed Face",R.drawable.disappointed_face));
        words.add(new Word("Worried Face",R.drawable.worried_face));
        words.add(new Word("Face With Steam From Nose",R.drawable.face_with_look_of_triumph));
        words.add(new Word("Crying Face",R.drawable.crying_face));
        words.add(new Word("Loudly Crying Face",R.drawable.loudly_crying_face));
        words.add(new Word("Frowning Face With Open Mouth",R.drawable.frowning_face_with_open_mouth));
        words.add(new Word("Anguished Face",R.drawable.anguished_face));
        words.add(new Word("Fearful Face",R.drawable.fearful_face));
        words.add(new Word("Weary Face",R.drawable.weary_face));
        words.add(new Word("Grimacing Face",R.drawable.grimacing_face));
        words.add(new Word("Face With Open Mouth & Cold Sweat",R.drawable.face_with_open_mouth_and_cold_sweat));
        words.add(new Word("Face Screaming in Fear",R.drawable.face_screaming_in_fear));
        words.add(new Word("Flushed Face",R.drawable.flushed_face));
        words.add(new Word("Dizzy Face",R.drawable.dizzy_face));
        words.add(new Word("Pouting Face",R.drawable.pouting_face));
        words.add(new Word("Angry Face",R.drawable.angry_face));
        words.add(new Word("Face With Medical Mask",R.drawable.face_with_medical_mask));
        words.add(new Word("Face With Thermometer",R.drawable.face_with_thermometer));
        words.add(new Word("Face With Head-Bandage",R.drawable.face_with_head_bandage));
        words.add(new Word("Nauseated Face",R.drawable.nauseated_face));
        words.add(new Word("Sneezing Face",R.drawable.sneezing_face));
        words.add(new Word("Smiling Face With Halo",R.drawable.smiling_face_with_halo));
        words.add(new Word("Cowboy Hat Face",R.drawable.face_with_cowboy_hat));
        words.add(new Word("Clown Face",R.drawable.clown_face));
        words.add(new Word("Lying Face",R.drawable.lying_face));
        words.add(new Word("Nerd Face",R.drawable.nerd_face));
        words.add(new Word("Smiling Face With Horns",R.drawable.smiling_face_with_horns));
        words.add(new Word("Angry Face With Horns",R.drawable.imp));
        words.add(new Word("Ogre",R.drawable.japanese_ogre));
        words.add(new Word("Goblin",R.drawable.japanese_goblin));
        words.add(new Word("Skull",R.drawable.skull));
        words.add(new Word("Ghost",R.drawable.ghost));
        words.add(new Word("Alien",R.drawable.alien_monster));
        words.add(new Word("Robot Face",R.drawable.robot_face));
        words.add(new Word("Pile of Poo",R.drawable.pile_of_poo));
        words.add(new Word("Smiling Cat Face With Open Mouth",R.drawable.smiling_cat_face_with_open_mouth));
        words.add(new Word("Grinning Cat Face With Smiling Eyes",R.drawable.grinning_cat_face_with_smiling_eyes));
        words.add(new Word("Cat Face With Tears of Joy",R.drawable.cat_face_with_tears_of_joy));
        words.add(new Word("Smiling Cat Face With Heart-Eyes",R.drawable.smiling_cat_face_with_heart_shaped_eyes));
        words.add(new Word("Cat Face With Wry Smile",R.drawable.cat_face_with_wry_smile));
        words.add(new Word("Kissing Cat Face With Closed Eyes",R.drawable.kissing_cat_face_with_closed_eyes));
        words.add(new Word("Weary Cat Face",R.drawable.weary_cat_face));
        words.add(new Word("Crying Cat Face",R.drawable.crying_cat_face));
        words.add(new Word("Pouting Cat Face",R.drawable.pouting_cat_face));
        words.add(new Word("Baby",R.drawable.baby));
        words.add(new Word("Boy",R.drawable.boy));
        words.add(new Word("Girl",R.drawable.girl));
        words.add(new Word("Man",R.drawable.man));
        words.add(new Word("Woman",R.drawable.woman));
        words.add(new Word("Old Man",R.drawable.older_man));
        words.add(new Word("Old Woman",R.drawable.older_woman));
        words.add(new Word("Man Health Worker",R.drawable.male_health_worker));
        words.add(new Word("Woman Health Worker",R.drawable.female_health_worker));
        words.add(new Word("Man Student",R.drawable.male_student));
        words.add(new Word("Woman Student",R.drawable.female_student));
        words.add(new Word("Man Judge",R.drawable.male_judge));
        words.add(new Word("Woman Judge",R.drawable.female_judge));
        words.add(new Word("Man Farmer",R.drawable.male_farmer));
        words.add(new Word("Woman Farmer",R.drawable.female_farmer));
        words.add(new Word("Man Cook",R.drawable.male_cook));
        words.add(new Word("Woman Cook",R.drawable.female_cook));
        words.add(new Word("Man Mechanic",R.drawable.male_mechanic));
        words.add(new Word("Woman Mechaninc",R.drawable.female_mechanic));
        words.add(new Word("Man Factory Worker",R.drawable.male_factory_worker));
        words.add(new Word("Woman Factory Worker",R.drawable.female_factory_worker));
        words.add(new Word("Man Office Worker",R.drawable.male_office_worker));
        words.add(new Word("Woman Office Worker",R.drawable.female_office_worker));
        words.add(new Word("Man Scientist",R.drawable.male_scientist));
        words.add(new Word("Woman Scientist",R.drawable.female_scientist));
        words.add(new Word("Man Technologist",R.drawable.male_technologist));
        words.add(new Word("Woman Technologist",R.drawable.female_technologist));
        words.add(new Word("Man Singer",R.drawable.male_singer));
        words.add(new Word("Woman Singer",R.drawable.female_singer));
        words.add(new Word("Man Artist",R.drawable.male_artist));
        words.add(new Word("Woman Artist",R.drawable.female_artist));
        words.add(new Word("Man Pilot",R.drawable.male_pilot));
        words.add(new Word("Woman Pilot",R.drawable.female_pilot));
        words.add(new Word("Man Astronaut",R.drawable.male_astronaut));
        words.add(new Word("Woman Astronaut",R.drawable.female_astronaut));
        words.add(new Word("Man Firefighter",R.drawable.male_firefighter));
        words.add(new Word("Woman Firefighter",R.drawable.female_firefighter));
        words.add(new Word("Police Officer",R.drawable.police_officer));
        words.add(new Word("Man Police Officer",R.drawable.male_police_officer));
        words.add(new Word("Woman Police Officer",R.drawable.female_police_officer));
        words.add(new Word("Detective",R.drawable.sleuth_or_spy));
        words.add(new Word("Man Detective",R.drawable.male_sleuth));
        words.add(new Word("Woman Detective",R.drawable.female_sleuth));
        words.add(new Word("Guard",R.drawable.guardsman));
        words.add(new Word("Man Guard",R.drawable.male_guard));
        words.add(new Word("Woman Guard",R.drawable.female_guard));
        words.add(new Word("Construction Worker",R.drawable.construction_worker));
        words.add(new Word("Man Construction Worker",R.drawable.male_construction_worker));
        words.add(new Word("Woman Construction Worker",R.drawable.female_construction_worker));
        words.add(new Word("Prince",R.drawable.prince));
        words.add(new Word("Princess",R.drawable.princess));
        words.add(new Word("Person Wearing Turban",R.drawable.man_with_turban));
        words.add(new Word("Man Wearing Turban",R.drawable.man_wearing_turban));
        words.add(new Word("Woman Wearing Turban",R.drawable.woman_wearing_turban));
        words.add(new Word("Man With Chinese Cap",R.drawable.man_with_gua_pi_mao));
        words.add(new Word("Blond-Haired Person",R.drawable.person_with_blond_hair));
        words.add(new Word("Blond-Haired Men",R.drawable.blond_man));
        words.add(new Word("Blond-Haired Woman",R.drawable.blonde_woman));
        words.add(new Word("Man in Tuxedo",R.drawable.man_in_tuxedo));
        words.add(new Word("Bride With Veil",R.drawable.bride_with_veil));
        words.add(new Word("Pregnant Woman",R.drawable.pregnant_woman));
        words.add(new Word("Baby Angel",R.drawable.baby_angel));
        words.add(new Word("Santa Claus",R.drawable.father_christmas));
        words.add(new Word("Mrs. Claus",R.drawable.mother_christmas));
        words.add(new Word("Person Frowning",R.drawable.person_frowning));
        words.add(new Word("Man Frowning",R.drawable.man_frowning));
        words.add(new Word("Woman Frowning",R.drawable.woman_frowning));
        words.add(new Word("Person Pouting",R.drawable.pouting_face));
        words.add(new Word("Man Pouting",R.drawable.man_pouting));
        words.add(new Word("Woman Pouting",R.drawable.woman_pouting));
        words.add(new Word("Person Gesturing No",R.drawable.face_with_no_good_gesture));
        words.add(new Word("Man Gesturing No",R.drawable.man_gesturing_not_ok));
        words.add(new Word("Woman Gesturing No",R.drawable.woman_gesturing_not_ok));
        words.add(new Word("Person Gesturing OK",R.drawable.face_with_ok_gesture));
        words.add(new Word("Man Gesturing OK",R.drawable.man_gesturing_ok));
        words.add(new Word("Woman Gesturing OK",R.drawable.woman_gesturing_ok));
        words.add(new Word("Person Tipping Hand",R.drawable.information_desk_person));
        words.add(new Word("Man Tipping Hand",R.drawable.man_tipping_hand));
        words.add(new Word("Woman Tipping Hang",R.drawable.woman_tipping_hand));
        words.add(new Word("Person Raising Hand",R.drawable.happy_person_raising_one_hand));
        words.add(new Word("Man Raising Hand",R.drawable.man_raising_hand));
        words.add(new Word("Woman Raising Hand",R.drawable.woman_raising_hand));
        words.add(new Word("Person Bowing",R.drawable.person_bowing_deeply));
        words.add(new Word("Man Bowing",R.drawable.man_bowing_deeply));
        words.add(new Word("Woman Bowing",R.drawable.woman_bowing_deeply));
        words.add(new Word("Person Facepalming",R.drawable.face_palm));
        words.add(new Word("Man Facepalming",R.drawable.man_facepalming));
        words.add(new Word("Woman Facepalming",R.drawable.woman_facepalming));
        words.add(new Word("Person Shrugging",R.drawable.shrug));
        words.add(new Word("Man Shrugging",R.drawable.man_shrugging));
        words.add(new Word("Woman Shrugging",R.drawable.woman_shrugging));
        words.add(new Word("Person Getting Massage",R.drawable.face_massage));
        words.add(new Word("Man Getting Massage",R.drawable.man_getting_face_massage));
        words.add(new Word("Woman Getting Massage",R.drawable.woman_getting_face_massage));
        words.add(new Word("Person Getting Haircut",R.drawable.haircut));
        words.add(new Word("Man Getting Haircut",R.drawable.man_getting_haircut));
        words.add(new Word("Woman Getting Haircut",R.drawable.woman_getting_haircut));
        words.add(new Word("Person Walking",R.drawable.pedestrian));
        words.add(new Word("Man Walking",R.drawable.man_walking));
        words.add(new Word("Woman Walking",R.drawable.woman_walking));
        words.add(new Word("Person Running",R.drawable.runner));
        words.add(new Word("Man Running",R.drawable.man_running));
        words.add(new Word("Woman Running",R.drawable.woman_walking));
        words.add(new Word("Man Dancing",R.drawable.man_dancing));
        words.add(new Word("Woman Dancing",R.drawable.dancer));
        words.add(new Word("People With Bunny Ears Partying",R.drawable.woman_with_bunny_ears));
        words.add(new Word("Men With Bunny Ears Partying",R.drawable.men_with_bunny_ears_partying));
        words.add(new Word("Women With Bunny Ears Partying",R.drawable.women_with_bunny_ears_partying));
        words.add(new Word("Man in Business Suit Levitating",R.drawable.man_in_business_suit_levitating));
        words.add(new Word("Speaking Head",R.drawable.speaking_head_in_silhouette));
        words.add(new Word("Bust in Silhouette",R.drawable.bust_in_silhouette));
        words.add(new Word("Busts in Silhouette",R.drawable.busts_in_silhouette));
        words.add(new Word("Man and Woman Holding Hands",R.drawable.man_and_woman_holding_hands));
        words.add(new Word("Two Men Holding Hands",R.drawable.two_men_holding_hands));
        words.add(new Word("Two Women Holding Hands",R.drawable.two_women_holding_hands));
        words.add(new Word("Kiss",R.drawable.kiss));
        words.add(new Word("Kiss: Man, Man",R.drawable.kiss_man_man));
        words.add(new Word(" Kiss: Woman, Woman",R.drawable.kiss_woman_woman));
        words.add(new Word("Couple With Heart",R.drawable.couple_with_heart));
        words.add(new Word("Couple With Heart: Man, Man",R.drawable.couple_with_heart_man_man));
        words.add(new Word("Couple With Heart: Woman, Woman",R.drawable.couple_with_heart_woman_woman));
        words.add(new Word("Family",R.drawable.family));
        words.add(new Word("Family: Man, Woman, Boy",R.drawable.family_man_woman_boy));
        words.add(new Word("Family: Man, Woman, Girl",R.drawable.family_man_woman_girl));
        words.add(new Word("Family: Man, Woman, Girl, Boy",R.drawable.family_man_woman_girl_boy));
        words.add(new Word("Family: Man, Woman, Boy, Boy",R.drawable.family_man_woman_boy_boy));
        words.add(new Word("Family: Man, Woman, Girl, Girl",R.drawable.family_man_woman_girl_girl));
        words.add(new Word("Family: Man, Man, Boy",R.drawable.family_man_man_boy));
        words.add(new Word("Family: Man, Man, Girl",R.drawable.family_man_man_girl));
        words.add(new Word("Family: Man, Man, Girl, Boy",R.drawable.family_man_man_girl_boy));
        words.add(new Word("Family: Man, Man, Boy, Boy",R.drawable.family_man_man_boy_boy));
        words.add(new Word("Family: Man, Man, Girl, Girl",R.drawable.family_man_man_girl_girl));
        words.add(new Word("Family: Woman, Woman, Boy",R.drawable.family_woman_woman_boy));
        words.add(new Word("Family: Woman, Woman, Girl",R.drawable.family_woman_woman_girl));
        words.add(new Word("Family: Woman, Woman, Girl, Boy",R.drawable.family_woman_woman_girl_boy));
        words.add(new Word("Family: Woman, Woman, Boy, Boy",R.drawable.family_woman_woman_boy_boy));
        words.add(new Word("Family: Woman, Woman, Girl, Girl",R.drawable.family_woman_woman_girl_girl));
        words.add(new Word("Family: Man, Boy",R.drawable.family_man_boy));
        words.add(new Word("Family: Man, Boy, Boy",R.drawable.family_man_boy_boy));
        words.add(new Word("Family: Man, Girl",R.drawable.family_man_girl));
        words.add(new Word("Family: Man, Girl, Boy",R.drawable.family_man_girl_boy));
        words.add(new Word("Family: Man, Girl, Girl",R.drawable.family_man_girl_girl));
        words.add(new Word("Family: Woman, Boy",R.drawable.family_woman_boy));
        words.add(new Word("Family: Woman, Boy, Boy",R.drawable.family_woman_boy_boy));
        words.add(new Word("Family: Woman, Girl",R.drawable.family_woman_girl));
        words.add(new Word("Family: Woman, Girl, Boy",R.drawable.family_woman_girl_boy));
        words.add(new Word("Family: Woman, Girl, Girl",R.drawable.family_woman_girl_girl));
        words.add(new Word("Selfie",R.drawable.selfie));
        words.add(new Word("Flexed Biceps",R.drawable.flexed_biceps));
        words.add(new Word("Backhand Index Pointing Left",R.drawable.white_left_pointing_backhand_index));
        words.add(new Word("Backhand Index Pointing Right",R.drawable.white_right_pointing_backhand_index));
        words.add(new Word("Index Pointing Up",R.drawable.white_up_pointing_index));
        words.add(new Word("Backhand Index Pointing Up",R.drawable.white_up_pointing_backhand_index));
        words.add(new Word("Middle Finger",R.drawable.reversed_hand_with_middle_finger_extended));
        words.add(new Word("Backhand Index Pointing Down",R.drawable.white_down_pointing_backhand_index));
        words.add(new Word("Victory Hand",R.drawable.victory_hand));
        words.add(new Word("Crossed Fingers",R.drawable.hand_with_index_and_middle_fingers_crossed));
        words.add(new Word("Vulcan Salute",R.drawable.raised_hand_with_part_between_middle_and_ring_fingers));
        words.add(new Word("Sign of the Horns",R.drawable.sign_of_the_horns));
        words.add(new Word("Raised Hand With Fingers Splayed",R.drawable.raised_hand_with_fingers_splayed));
        words.add(new Word("Raised Hand",R.drawable.raised_hand));
        words.add(new Word("OK Hand",R.drawable.ok_hand_sign));
        words.add(new Word("Thumbs Up",R.drawable.thumbs_up_sign));
        words.add(new Word("Thumbs Down",R.drawable.thumbs_down_sign));
        words.add(new Word("Raised Fist",R.drawable.raised_fist));
        words.add(new Word("Oncoming Fist",R.drawable.fisted_hand_sign));
        words.add(new Word("Left-Facing Fist",R.drawable.left_facing_fist));
        words.add(new Word("Right-Facing Fist",R.drawable.right_facing_fist));
        words.add(new Word("Waving Hand",R.drawable.waving_hand_sign));
        words.add(new Word("Writing Hand",R.drawable.writing_hand));
        words.add(new Word("Clapping Hands",R.drawable.clapping_hands_sign));
        words.add(new Word("Open Hands",R.drawable.open_hands_sign));
        words.add(new Word("Raising Hands",R.drawable.person_raising_both_hands_in_celebration));
        words.add(new Word("Folded Hands",R.drawable.person_with_folded_hands));
        words.add(new Word("Handshake",R.drawable.handshake));
        words.add(new Word("Nail Polish",R.drawable.nail_polish));
        words.add(new Word("Ear",R.drawable.ear));
        words.add(new Word("Nose",R.drawable.nose));
        words.add(new Word("Footprints",R.drawable.footprints));
        words.add(new Word("Eyes",R.drawable.eyes));
        words.add(new Word("Eye",R.drawable.eye));
        words.add(new Word("Tongue",R.drawable.tongue));
        words.add(new Word("Mouth",R.drawable.mouth));
        words.add(new Word("Kiss Mark",R.drawable.kiss_mark));
        words.add(new Word("Glasses",R.drawable.eyeglasses));
        words.add(new Word("Sunglasses",R.drawable.dark_sunglasses));
        words.add(new Word("Necktie",R.drawable.necktie));
        words.add(new Word("T-Shirt",R.drawable.t_shirt));
        words.add(new Word("Jeans",R.drawable.jeans));
        words.add(new Word("Dress",R.drawable.dress));
        words.add(new Word("Kimono",R.drawable.kimono));
        words.add(new Word("Bikini",R.drawable.bikini));
        words.add(new Word("Woman’s Clothes", R.drawable.womans_clothes));
        words.add(new Word("Purse",R.drawable.purse));
        words.add(new Word("Handbag",R.drawable.handbag));
        words.add(new Word("Clutch Bag",R.drawable.pouch));
        words.add(new Word("School Backpack",R.drawable.school_satchel));
        words.add(new Word("Man’s Shoe",R.drawable.mans_shoe));
        words.add(new Word("Running Shoe",R.drawable.athletic_shoe));
        words.add(new Word("High-Heeled Shoe",R.drawable.high_heeled_shoe));
        words.add(new Word("Woman’s Sandal",R.drawable.womans_sandal));
        words.add(new Word("Woman’s Boot",R.drawable.womans_boots));
        words.add(new Word("Crown",R.drawable.crown));
        words.add(new Word("Woman’s Hat",R.drawable.womans_hat));
        words.add(new Word("Top Hat",R.drawable.top_hat));
        words.add(new Word("Graduation Cap",R.drawable.graduation_cap));
        words.add(new Word("Rescue Worker’s Helmet",R.drawable.helmet_with_white_cross));
        words.add(new Word("Lipstick",R.drawable.lipstick));
        words.add(new Word("Ring",R.drawable.ring));
        words.add(new Word("Closed Umbrella",R.drawable.closed_umbrella));
        words.add(new Word("Umbrella",R.drawable.umbrella));
        words.add(new Word("Briefcase",R.drawable.briefcase));

        MeaningAdapter adapter = new MeaningAdapter(this, words, R.color.category_smileys_people);

        ListView listView = (ListView) findViewById(R.id.meaning_list_1);

        listView.setAdapter(adapter);

    }
}
